sudo: required
language: bash
env:
  global:
  - BUILD_NAME=Perrinn424-webgl
  - secure: gjMhTDn+3AnDPsnkc/aQUgfVKn7xf8VQt/ScjWMfd+476mZRW5UPnkPtG9/8/djKQeWl2g++p4rFL19PxGB9MXxY3ylsNvE0bCAn9xyI75+5Mszh0xS9E6k5GICjqJLd0gAfUWm6sY4ukoMxBg0k7duyj6/fhwxYtHuJral4qU4KH+NdGpP0xqC7zw8gT0Ze4aBHqr36HEbMAE+YN8vuJauOSZqwM2SYQ6CTmN1MXw2S6n2LCh3OQKw64zQhshn0ieZ11yFjlKfxUXVK+C/FDlSoYoLByDbhGvKMPq0w2eUT30Dc4WuzYmD0WStbU7tMI7ZjyKcSzmU6NsAHnlkPYJojXOd4YU09rFtlEBw+40TNN86N7I5VeGN98BmJ+XCqYc5ffBxcGMb7qRQyjjCQPjTpa776HIFhVWGOSSbN3qC7Rpd1v8O7DXhTnBCxFTBEL8ol+uCmNXzcdR0e4efiE/zCCop/HUwsOlDndhIFtHozWgsqpSw5Vx8+kfR8BIEV1hHpPNJG8PoYhGm9sEsToH9M+EumvpLBnsV8DYvgchFdGVxU+vQn0UAFRjD6PH0Vuda3g5ydj+ZjEC8rZaqAlBDfAzHLsNeXuQ64UTxFBFXdvaMupvoDaYOLhAx8VOjtNdCqb+A0kqTBhY8Fr71h4fQ1d5WnOdMwp8oCrufaSXQ=
services:
- docker
before_install:
- openssl aes-256-cbc -K $enck -iv 0 -in Unity_v2019.x.ulf.enc -out ./Unity_v2019.x.ulf -d
- export UNITY_LICENSE=`cat Unity_v2019.x.ulf`
- rm Unity_v2019.x.ulf
- docker pull $IMAGE_NAME
jobs:
  include:
  - stage: build
    env: BUILD_TARGET=WebGL IMAGE_NAME=gableroux/unity3d:2019.4.14f1-webgl
    script: chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh
