# This is a basic workflow to help you get started with Actions

name: Activation License Workflow

# Controls when the action will run. 
on: workflow_dispatch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  activation:
    name: Requesting License
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2019.4.18f1
    steps:
      - name: Request Activation File
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: ${{ matrix.unityVersion }}
      - name: Uploading License in artficats
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
